# Dataset
supports: 11151
train_split: [100, 20, 10]
image_size: 128
font_size: 110
batch_size: 32

# Model
model: ConvNext
blocks: [3, 3, 3, 3]
channels: [32, 64, 128, 256]
content_emb_dim: 1024
mlp_hidden: 1024
mlp_layers: 5
warmup: 100
lr: 0.0001
factor: 0.99
patience: 5
max_epochs: 10000
log_weight_ratio: 10

plot: True